[workspace]
resolver = "2"
members = ["crates/curfew-core", "crates/curfew-cli", "crates/curfew-ics", "crates/curfew-ffi", "crates/curfew-sync", "crates/curfew-win", "crates/curfew-svc", "crates/curfew-tray"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.82"
license = "AGPL-3.0-or-later"
repository = "https://github.com/Satwik-Miyyapuram/curfew"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
toml = "0.8"
thiserror = "2"
chrono = { version = "0.4", default-features = false, features = ["alloc", "serde"] }
chrono-tz = { version = "0.10", default-features = false, features = ["std"] }
serde_json = "1"
uniffi = "0.28"
ed25519-dalek = { version = "2", features = ["rand_core", "serde"] }
x25519-dalek = { version = "2", features = ["static_secrets"] }
chacha20poly1305 = "0.10"
sha2 = "0.10"
rand_core = { version = "0.6", features = ["getrandom"] }
