"""Generate the "what is still open" list from the coverage tables, so it cannot drift.

**The `## Still open` section has been wrong three times**, and it says so itself: it left 18 of 48
findings unmentioned once (entry 46), mis-filed three P1s as P2 once, and this round it still claimed
*"F-18 (P0) — Windows cannot pair a device"* and *"F-2, F-34, F-48, F-49 — not re-assessed"* after all five
were done. Its own diagnosis is right — *"it kept grouping work by an assumption about how the work must be
verified rather than by what the work is"* — and the fix it never applied to itself is the one used for the
coverage tables: **generate the list from the table instead of rewriting it from memory.**

So the list between the markers is derived, and `tools/check_log.py` verifies it matches. The prose around
it stays hand-written, because the lessons are the part a generator cannot supply.
"""
import pathlib
import sys
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
LOG = ROOT / "FIXES.md"

BEGIN = "<!-- open:begin — generated by tools/open_rows.py; do not edit by hand -->"
END = "<!-- open:end -->"


def rows(text):
    """Every coverage row, as (id, severity, status)."""
    out = {}
    for line in text.splitlines():
        m = re.match(r"^\| (F-\d+|P\d+-\d+) \| ([A-Z0-9]+) \| (.*?) \|$", line)
        if m:
            out[m.group(1)] = (m.group(2), m.group(3))
    return out


# The vocabulary the coverage tables actually use, **read off the table** rather than guessed.
#
# `"fixed" not in status` was the first version. It classified **"Not fixed"** as closed — as did "Unfixed"
# and "Open - not fixed" — while "Deferred, see entry 4" read as closed via "entry". A generator whose
# entire job is to say what is still open would have printed "Nothing" for a table full of open rows.
#
# **Negatives are checked before the entry reference**, which is the actual fix: the old rule had no notion
# of a negative, so any status mentioning an entry was assumed to be closed. A status that is just
# `entry 12 — ...` *is* closed, because that is how the UX table records an earlier round's fix.
# **Explicit negatives**, checked before anything positive: "not fixed" contains "fixed".
OPEN_WORDS = (
    "not fixed",
    "unfixed",
    "deferred",
    "still open",
    "verified open",
    "not re-assessed",
    "unaddressed",
    "blocked",
    "left open",
    "open pending",
    # **"not done" earns its place**: it is how these tables say a review claim is still outstanding, and
    # adding it surfaced two rows marked `fixed` whose own text said otherwise (P1-8, P2-8). Only two rows
    # in the table contain it and both were genuinely partial, so it cannot mask anything.
    #
    # **"pending" is deliberately absent.** P2-18 uses it as a technical term — *"every pending entry"* in
    # the op-log — so the word says nothing about the row's status. That is the difference between a
    # vocabulary and a word list, and it is why each entry here is checked against the table first.
    "not done",
    "still to do",
    # Verified safe by scanning all 52 statuses in the table: none of these appears in a closed row. The
    # exclusion of "pending" (a technical term in P2-18) and of "to do"/"todo" (which read as "how to do X"
    # in prose) is deliberate — a word list that is too keen turns a check into noise.
    "working on",
    "still being",
    "not yet",
    "unfinished",
    "outstanding",
    "incomplete",
    "unresolved",
    "awaiting",
    "needs work",
    "revisit",
)
CLOSED_WORDS = ("fixed", "not a defect", "assessed")
ENTRY_REF = re.compile(r"^\s*\**(entry|entries)\s+\d+")
# A bare "open", as a whole word — `\b` so "opened" does not match. Three statuses in the table contain
# "opened" and all three are closed, which is why this is not a substring test.
BARE_OPEN = re.compile(r"\bopen\b", re.IGNORECASE)


def classify(status):
    """`"closed"`, `"partly"` or `"open"` — or raises on a phrase this file does not know.

    **The order matters, and each step earns its place:**

    1. *partly* — because "partly fixed" contains "fixed".
    2. *explicit negatives* — because "not fixed" contains "fixed".
    3. *explicit positives* — because three statuses containing "opened" are closed.
    4. *a bare "open"* — catches "left open" and "open pending", which is what a row citing an entry
       often says, and which the entry-reference fallback below used to swallow.
    5. *an entry reference* — `entry 1 — Lock::Timer removed from claimable` is how the UX table records
       an earlier round's fix, so this stays, but only as the **last** resort.

    Stepping straight from (2) to (5) — checking `CLOSED_WORDS or ENTRY_REF` together — classified
    `entry 14 — investigated and left open` as closed, which is the defect this ordering fixes.

    **The residual, stated rather than implied.** Step 5 is a wildcard: an `entry N — ...` status is closed
    unless one of the words above appears. So an incompleteness phrasing nobody listed reads as done. This
    narrows that; it does not close it, and no vocabulary over free prose can. The mitigation is that every
    word here was checked against the table before being added, and that a status matching *nothing* stops
    the tool instead of guessing.

    **Raises rather than guessing.** An unrecognised status word is the one case where stopping is right:
    treating it as open inflates the list, treating it as closed hides work, and either way the tool is
    confidently wrong about the thing it exists to report.
    """
    low = status.lower()
    if "partly fixed" in low or "partial" in low:
        return "partly"
    if any(w in low for w in OPEN_WORDS):
        return "open"
    if any(w in low for w in CLOSED_WORDS):
        return "closed"
    if BARE_OPEN.search(status):
        return "open"
    if ENTRY_REF.match(status):
        return "closed"
    raise SystemExit(
        f"tools/open_rows.py does not recognise the status {status!r}.\n"
        f"Add it to OPEN_WORDS or CLOSED_WORDS rather than letting this guess."
    )


def is_open(status):
    return classify(status) == "open"


def is_partly(status):
    return classify(status) == "partly"


def build(text):
    table = rows(text)
    # The design review's ids are `P<sev>-<n>`; the UX review's are `F-<n>`, and its severities are in the
    # table rather than in the id — so the grouping has to come from the row, not from the name.
    open_rows = {k: v for k, v in table.items() if is_open(v[1])}
    partly = {k: v for k, v in table.items() if is_partly(v[1])}

    lines = []
    by_sev = {}
    for fid, (sev, _status) in sorted(open_rows.items()):
        by_sev.setdefault(sev, []).append(fid)
    for sev in sorted(by_sev):
        # A finding whose id says what it is leads with that, so a reader can tell the two reviews apart.
        named = ", ".join(f"**{f}**" for f in by_sev[sev])
        lines.append(f"- **{sev}** — {len(by_sev[sev])} open: {named}")

    if partly:
        named = ", ".join(f"**{f}**" for f in sorted(partly))
        lines.append(f"- **Partly fixed** — {len(partly)}: {named}")

    if not open_rows and not partly:
        lines.append("- **Nothing.** Every finding in both reviews is fixed, or recorded with the reason it "
                     "is not a defect.")

    return "\n".join(lines)


def expected_block(text):
    """The block this file *would* write. `None` if the markers are missing."""
    if BEGIN not in text or END not in text:
        return None
    return f"{BEGIN}\n\n{build(text)}\n\n{END}"


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv

    # **`--print` exists so a checker can compare against what this *would* write.** The first attempt at
    # making `check_log.py` read-only had it run `--check` and then read the block back out of `FIXES.md`
    # — which returns the file's own content, so the comparison could never fail. Printing the expected
    # block is the only version that can disagree.
    if "--print" in argv:
        expected = expected_block(LOG.read_text(encoding="utf-8"))
        if expected is None:
            print("the open-list markers are missing from FIXES.md", file=sys.stderr)
            return 1
        # No trailing newline: the caller compares this by equality against the text in the file.
        sys.stdout.write(expected)
        return 0

    # `--check` reports without writing, for a human.
    checking = "--check" in argv

    text = LOG.read_text(encoding="utf-8")
    expected = expected_block(text)
    if expected is None:
        print("  ERROR the open-list markers are missing from FIXES.md")
        return 1
    before = text[text.index(BEGIN) : text.index(END) + len(END)]
    if before == expected:
        print("  ok   the open list already matches the table")
        return 0
    if checking:
        # To stderr, so stdout carries only the expected block for a caller that wants to diff it.
        print("  FAIL the open list does not match the coverage tables", file=sys.stderr)
        return 1
    LOG.write_text(text.replace(before, expected, 1), encoding="utf-8")
    print(f"  rewrote the open list from the table:\n{build(text)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
