"""Generate the "what is still open" list from the coverage tables, so it cannot drift.

**The `## Still open` section has been wrong three times**, and it says so itself: it left 18 of 48
findings unmentioned once (entry 46), mis-filed three P1s as P2 once, and this round it still claimed
*"F-18 (P0) — Windows cannot pair a device"* and *"F-2, F-34, F-48, F-49 — not re-assessed"* after all five
were done. Its own diagnosis is right — *"it kept grouping work by an assumption about how the work must be
verified rather than by what the work is"* — and the fix it never applied to itself is the one used for the
coverage tables: **generate the list from the table instead of rewriting it from memory.**

So the list between the markers is derived, and `tools/check_log.py` verifies it matches. The prose around
it stays hand-written, because the lessons are the part a generator cannot supply.
"""
import pathlib
import sys
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
LOG = ROOT / "FIXES.md"

BEGIN = "<!-- open:begin — generated by tools/open_rows.py; do not edit by hand -->"
END = "<!-- open:end -->"


def rows(text):
    """Every coverage row, as (id, severity, status)."""
    out = {}
    for line in text.splitlines():
        m = re.match(r"^\| (F-\d+|P\d+-\d+) \| ([A-Z0-9]+) \| (.*?) \|$", line)
        if m:
            out[m.group(1)] = (m.group(2), m.group(3))
    return out


# **The verdict is the leading word of the status cell, and only that.** Scanning the whole cell for
# negative phrases cannot tell *"this is outstanding"* from *"this is excluded on purpose, here is why"* —
# P1-8's row says "two things are deliberately not done" and is nevertheless fixed — and every word added to
# narrow one case widened the other.
#
# The rows already lead with their verdict, so this reads that and ignores the explanation. The earlier
# versions of this function were substring tests over the prose, and they were wrong three times: "fixed" not
# in status classified **"Not fixed"** as closed; treating an entry reference as closed swallowed
# `entry 14 — investigated and left open`; and then the word list that fixed that swallowed a *fixed* row
# that mentioned an exclusion.
#
# The patterns are anchored, and order matters: "not fixed" before "fixed", "not a defect" before "not".
LEADING = (
    (re.compile(r"partly fixed|partial"), "partly"),
    (re.compile(r"not fixed|unfixed|deferred|blocked|unaddressed|not re-assessed|still open|"
                r"open\b|left open"), "open"),
    (re.compile(r"not a defect"), "closed"),
    (re.compile(r"fixed|assessed|reconciled|rejected"), "closed"),
)
# **No entry-reference pattern, deliberately.** Treating `entry N — ...` as closed is what swallowed
# `entry 14 — investigated and left open`: the form carries no verdict, so the tool supplied one. Rows that
# used it now lead with `**Fixed** (entry N)`, and a row that leads with a bare reference stops the tool
# rather than being assumed closed.


def classify(status):
    """`"closed"`, `"partly"` or `"open"` — from the **leading** verdict, or raises if there is none.

    Only the beginning of the cell is read, because the rest of it is the explanation and the explanation
    legitimately contains negative words. A row that does not begin with a verdict this file knows is the one
    case where stopping is right: guessing would either inflate the open list or hide work, and either way
    the tool would be confidently wrong about the thing it exists to report.
    """
    # Strip the markdown emphasis and whitespace the tables wrap the verdict in.
    lead = status.lstrip().lstrip("*").lstrip().lower()
    for pattern, verdict in LEADING:
        if pattern.match(lead):
            return verdict
    raise SystemExit(
        f"tools/open_rows.py cannot read a verdict at the start of {status[:60]!r}.\n"
        f"Lead the cell with a verdict: fixed, partly fixed, not fixed, not a defect, assessed, "
        f"open, rejected -- with the entry reference after it, as `**Fixed** (entry 12) ...`."
    )


def is_open(status):
    return classify(status) == "open"


def is_partly(status):
    return classify(status) == "partly"


def build(text):
    table = rows(text)
    # The design review's ids are `P<sev>-<n>`; the UX review's are `F-<n>`, and its severities are in the
    # table rather than in the id — so the grouping has to come from the row, not from the name.
    open_rows = {k: v for k, v in table.items() if is_open(v[1])}
    partly = {k: v for k, v in table.items() if is_partly(v[1])}

    lines = []
    by_sev = {}
    for fid, (sev, _status) in sorted(open_rows.items()):
        by_sev.setdefault(sev, []).append(fid)
    for sev in sorted(by_sev):
        # A finding whose id says what it is leads with that, so a reader can tell the two reviews apart.
        named = ", ".join(f"**{f}**" for f in by_sev[sev])
        lines.append(f"- **{sev}** — {len(by_sev[sev])} open: {named}")

    if partly:
        named = ", ".join(f"**{f}**" for f in sorted(partly))
        lines.append(f"- **Partly fixed** — {len(partly)}: {named}")

    if not open_rows and not partly:
        lines.append("- **Nothing.** Every finding in both reviews is fixed, or recorded with the reason it "
                     "is not a defect.")

    return "\n".join(lines)


def expected_block(text):
    """The block this file *would* write. `None` if the markers are missing."""
    if BEGIN not in text or END not in text:
        return None
    return f"{BEGIN}\n\n{build(text)}\n\n{END}"


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv

    # **`--print` exists so a checker can compare against what this *would* write.** The first attempt at
    # making `check_log.py` read-only had it run `--check` and then read the block back out of `FIXES.md`
    # — which returns the file's own content, so the comparison could never fail. Printing the expected
    # block is the only version that can disagree.
    if "--print" in argv:
        expected = expected_block(LOG.read_text(encoding="utf-8"))
        if expected is None:
            print("the open-list markers are missing from FIXES.md", file=sys.stderr)
            return 1
        # No trailing newline: the caller compares this by equality against the text in the file.
        sys.stdout.write(expected)
        return 0

    # `--check` reports without writing, for a human.
    checking = "--check" in argv

    text = LOG.read_text(encoding="utf-8")
    expected = expected_block(text)
    if expected is None:
        print("  ERROR the open-list markers are missing from FIXES.md")
        return 1
    before = text[text.index(BEGIN) : text.index(END) + len(END)]
    if before == expected:
        print("  ok   the open list already matches the table")
        return 0
    if checking:
        # To stderr, so stdout carries only the expected block for a caller that wants to diff it.
        print("  FAIL the open list does not match the coverage tables", file=sys.stderr)
        return 1
    LOG.write_text(text.replace(before, expected, 1), encoding="utf-8")
    print(f"  rewrote the open list from the table:\n{build(text)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
